### ISSUE TITLE
create the map layout of the laboratory

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#103]
### Description

Create a map and relevant documentation of this location.

### Acceptance Criteria

The Map & Relevant documentation has been completed and placed into the wiki.
The Map & Relevant documentation follow the outline https://github.com/alexitsios/Calamity/wiki/Story-Bible#outline 

- Contains locations of Dr. Laio's body, flamethrower, cipher puzzle, acid substance components, and plaques
- Has description's of the rooms/locations
- Has locations of camera angles

**Comment by chaserimmer** [comment]
@cloudphobos @alexitsios 
map and layout uploaded.
Ready for art to be designed around the placement and layout of rooms in laboratory.

**Comment by mashewmake** [comment]
Has been reviewed. Looks good to me.

**Comment by alexitsios** [comment]
@chaserimmer it's not clear to me what the 3d artist needs to do here. I suggest we close the task.

**Comment by alexitsios** [comment]
@DimitrisKalyvas @FreelanceSeven @ChristosDav @cloudphobos  @nicolai21 please provide your feedback here.

**Comment by alexitsios** [comment]
hey @chaserimmer buddy!

By the positioning of the items, it seems to me that the location is a single room/place. Since this is a 3d horror game, we should give emphasis on long corridors and narrow spaces. 

I'm attaching the map/layout for the laboratory from one of the resident evil games.

![Image](https://user-images.githubusercontent.com/11029768/222984915-a5f79497-a373-4729-a099-33280db55e39.png)

Note that all the above is just feedback, you are to decide if edits are needed based on the feedback everyone provides since you know your work items better.

**Comment by chaserimmer** [comment]
Updated layout. Let me know if this is more along the lines. I believe the lab in RE has much more due to the levels i.e. upstairs, downstairs, that we don't really have outlined in the GDD for Calamity specifically.


![Image](https://user-images.githubusercontent.com/126846200/223202155-261b3432-efb9-4a69-a7b7-e3310ee3f6d6.png)

**Comment by alexitsios** [comment]
Hey @chaserimmer Chase Buddy,

New iteration of the map looks better, but I think we're still not solving the issue of a wide, open area.

When I created the https://github.com/alexitsios/Calamity/wiki/Locations#laboratory I provided a short description and an indicative list of material to get everyone started, but not so detailed to limit level designers.

Imo the main area of the laboratory could be split into several rooms, maybe in a circular order, and these would be:

- Reception area: This is where visitors are greeted and checked-in.
- Equipment room: This room stores all the lab equipment, such as microscopes, centrifuges, and pipettes.
- Prep room: This is where lab technicians prepare samples for analysis.
- Analytical room: This is where the actual analysis takes place, using the lab equipment and chemicals.
- Clean room: This is a sterile environment used for certain types of experiments.
- Cold room: This is a refrigerated room used for storing samples or even tubes with the infected etc that need to be kept at a low temperature.
- Animal testing room: This is where both humans and animals are kept for experiments.
- Offices: Various offices of the personnel and the scientists. Also a good place for Cassandra to find files, memos, and diaries.
- Break room: This is where lab personnel can take a break and eat.
- Small warehouse: where cleaners can have their cleaning stuff (gloves, cleaning chemical, vacuums etc.)

FYI @mashewmake @DimitrisKalyvas @cloudphobos @ChristosDav @FreelanceSeven

**Comment by chaserimmer** [comment]
Thanks for the detailed points of the lab vision. I'll work on this and upload the updated layout once complete. @alexitsios

**Comment by nicolai21** [comment]
Most of these rooms could be closer or attached to the large one to help.  This would also allow for some puzzles or incentives to explore.

**Comment by chaserimmer** [comment]
I agree with @nicolai21 . But then I think we need to add some interaction into these other rooms for player incentive.

**Comment by alexitsios** [comment]
@chaserimmer depends on the level of interation you want and the story each room has.

Etc. where Dr. Laios' human body is, you could have his carcass and notes of what he did to himself, how he got wounded, his last moments.

Another room could feature a man holding a knife and a dead infected nearby -> giving to the player the narrative of what happened: the scientist fought and both killed themselves.

If you want additional barks, memos, diaries, etc. the narrative team can write them down for you.

Also, the list of rooms I placed are indicative as I've said, hoping to give you an idea of how to split a big area into several smaller.

**Comment by chaserimmer** [comment]
If you want to go even more labyrinth style, let me know.

**Comment by alexitsios** [comment]
My main concern was the wide space, and your new iteration solves this! 

As additional feedback you might want to consider adding corridors to connect some areas so that you don't have to pass from the reception all the time. These don't need to be open from the get go, but can open as the game progresses. Again, this is entirely optional.

Good job @chaserimmer !

**Comment by FreelanceSeven** [comment]
I really like how the map looks now. Very sci-fi and very fitting, with plenty of opportunities for closed-in spaces. This might be the one!

**Comment by ChristosDav** [comment]
The design is awesome! Nice work @chaserimmer . Waiting on the room setup in order to have a clearer view. Meanwhile, I'm working with @FreelanceSeven on the writing for the lab and we'll provide feedback again when needed.

**Comment by DimitrisKalyvas** [comment]
I like the current iteration but please provide some more details on what each number for each room means. You should also mention where the player finds the key to each locked door.

**Comment by chaserimmer** [comment]
@DimitrisKalyvas The initial iteration has the room explanations. Since 8 more rooms were added, I am waiting on some of the narrative work regarding those rooms to emerge. Also, there aren't keys. There are the 3 substances found around the rooms as shown (stated in the GDD) which just unlocks the armory. All the other doors are unlocked except the code needed to get into the control room. Which is 'unlock' or solving the cipher puzzle.

**Comment by alexitsios** [comment]
@chaserimmer if the task is complete, you can upload the new map to https://github.com/alexitsios/Calamity/wiki/Locations#laboratory with some context of the locations etc 1. reception area and close this issue!

Again, nice work! Looking forward to see how the level will look like.

**Comment by alexitsios** [comment]
@mashewmake can you take over this task? I think the layout is ready, but feel free to redesign it if you see fit.

FYI @seekeroftheball @Unicornosplendente

**Comment by Unicornosplendente** [comment]
@alexitsios this is almost completed, It's just having some changes, as soon as is completed, it will be moved

fyi @seekeroftheball

**Comment by mashewmake** [comment]
Updated the map layout. This is now completed. fyi @Unicornosplendente

**Comment by crtherin** [comment]
@mashewmake can you update this to include camera views?

**Comment by mashewmake** [comment]
Map has been updated with camera views. @crtherin
