### ISSUE TITLE
Create general environmental items for the cemetery

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#114]
### Description
Create the general items of the laboratory

### Acceptance Criteria

- Create low-poly 3d assets (props, environmental art), referring to the related documentation here https://github.com/alexitsios/Calamity/wiki/Locations#cemetery
- The assets should be fully textured.
- The assets are uploaded into the relevant google folder https://drive.google.com/drive/u/0/folders/1EFHYYqpdzWFVnWEovP-p72EI6CxQzqZu

**Comment by alexitsios** [comment]
@FaceRadiation Hey Adrian buddy,

I'm assigning you this task, it's basically what you've been working on, but I'm using this for simplicity's shake, instead of creating each item separately.

**Comment by Unicornosplendente** [comment]
Ca I close this one? @FaceRadiation 

fyi @alexitsios @crtherin

**Comment by alexitsios** [comment]
@FaceRadiation Hey Adrian. What's the status of this ticket?
