### ISSUE TITLE
Create the blockout of the Cemetery

### ISSUE THREAD

**Issue by DimitrisKalyvas** [alexitsios/Calamity#131]
### Description
The blockout of the cemetery

### Acceptance criteria

o Latest version of layout recreated in the engine
o Use 1 texture for the floor, 1 for the walls
o Include enemy/player metrics in encounter spots for a sense of scale
o Include available assets
o Gameplay cameras & player character added

**Comment by alexitsios** [comment]
@mashewmake is this done or should I move it to "in progress?" FYI @Unicornosplendente

**Comment by mashewmake** [comment]
It is in progress. @alexitsios @Unicornosplendente

**Comment by mashewmake** [comment]
blockout for cemetery has been finished for now and has a pull request waiting to be merged into develop
