### ISSUE TITLE
Create the blockout of the Laboratory

### ISSUE THREAD

**Issue by DimitrisKalyvas** [alexitsios/Calamity#132]
### Description
The blockout of the laboratory.

### Acceptance criteria

o Latest version of layout recreated in the engine
o Use 1 texture for the floor, 1 for the walls
o Include enemy/player metrics in encounter spots for a sense of scale
o Include available assets
o Gameplay cameras & player character added

**Comment by alexitsios** [comment]
@chaserimmer should I set this to in progress?

**Comment by FreelanceSeven** [comment]
1: Clean Room (?)
2: Prep Room
3: Analytical Room
4: Offices
5: Warehouse
6: Reception Room
7: Equipment Room
8: Cold Storage
9: Break Room
10: Control Room

**Comment by alexitsios** [comment]
@mashewmake after the #103 Map Layout of the Laboratory has been completed, you can get started with the block out of the laboratory. 

FYI @seekeroftheball @Unicornosplendente

**Comment by mashewmake** [comment]
Blockout of the Laboratory has been completed and meets all criteria. Marking as complete for now.
