### ISSUE TITLE
Create a list of all the gameplay mechanics for the programming department

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#135]
### Description

A list of all the gameplay programming tasks that the programmers need to make.

### Acceptance Criteria.

The list has been created and Jordan @seekeroftheball provided feedback in it.

**Comment by alexitsios** [comment]
@teberzin 

I'm attaching here the initial research I had done for the gameplay and functionality so that it helps you create the required list. @seekeroftheball @mistermostmad  FYI.

Epic 4: Gameplay and Functionality
As a player, I want to be able to move my character through the game environment using a controller or keyboard so that I can explore the world.
•	The type of movement controls (e.g. WASD, arrow keys, joystick)
•	The character's animations and physics
•	Collision detection and response with the environment
•	Camera movement and rotation
As a player, I want to be able to interact with objects in the game world using button prompts or other controls so that I can solve puzzles and progress through the game.
•	The type of interaction (e.g. picking up items, using levers, opening doors)
•	The animation and visual effects of the interaction
•	The logic of the interaction and how it affects the game world and the player's progress
•	The placement of the objects and the design of the puzzles
•	The integration of the interaction with the game's story and lore.
As a player, I want to be able to fight enemies using a variety of weapons and abilities so that I can defend myself and advance through the game.
•	The type of weapons and abilities available to the player (e.g. handgun, shotgun, melee weapons, special abilities)
•	The zombie' artificial intelligence and behavior
•	The animation and visual effects of the combat
•	The game mechanics of the combat system, such as hit detection, reloading, reloading and others
•	The integration of the combat system with the game's story, lore and atmosphere
•	The balancing of the combat difficulty and the player's progression.
As a player, I want to be able to save my progress and load it later so that I can pick up where I left off.
•	The method of saving progress (e.g. manual saves, auto-saves, cloud saves)
•	The frequency of saving progress
•	The data that needs to be saved (e.g. player's position, inventory, progress, etc.)
•	The method of loading progress (e.g. load game menu, quick saves/loads)
•	The security and integrity of the save data.
As a player, I want to be able to see my character's health, inventory, and other status information so that I can make informed decisions while playing.
•	The design and layout of the user interface
•	The placement of the health, inventory and other status information on the screen
•	The visualization of the information (e.g. numbers, bars, icons)
•	The updates of the information in real-time
•	The integration of the UI with other game systems, such as the combat system, inventory system and others.

**Comment by teberzin** [comment]
@alexitsios We can mark it as done since Jordan is okay with it.
