### ISSUE TITLE
Read and provide feedback on Coding Standards and Guidelines

### ISSUE THREAD

**Issue by seekeroftheball** [alexitsios/Calamity#138]
### Description
The programming standards and guidelines first draft is complete! Please read it over and provide feedback on the Discord programming thread. Please respond when you're done reading so we know everyone has at least read it. But we'd like you involved! So if you have any input or questions, please share! Reading it over and responding is the minimum. 

The code architecture page is being rewritten now so ignore references to that page until it's complete. We're also currently setting up the GitFlow pipelines described on the wiki.

### Acceptance Criteria:
All members of the programming team need to provide input or at least confirmation that they've read the Coding Standards and Guidelines.

Any member of the team that will be contributing files to the Unity project via GitHub need to at least read the last 3 sections of the Coding Standards and Guidelines. The sections relevant to your work are "Folders and Asset Structure",  "Packages", and "Git and Version Control".

@seekeroftheball will close this task once everyone has confirmed.

**Comment by alexitsios** [comment]
@seekeroftheball should we close this?
