### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by seekeroftheball** [alexitsios/Calamity#152]
### Description
Add any files that shouldn't be included in a pull request. Such as local Unity settings or layout files.

### Acceptance Criteria:
- Should exclude Unity files that shouldn't be regularly overwritten, and any art or audio files that may need excluded.
- Should exclude test environment files.

**Comment by chaserimmer** [comment]
PR created:
https://github.com/alexitsios/Calamity/pull/157
@seekeroftheball
