### ISSUE TITLE
Create 3d model of the Thing.

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#16]

**Comment by alexitsios** [comment]
@Skaers can you place in the description here the updated image of the creature so that Esso can start working on it?

**Comment by Skaers** [comment]
> @Skaers can you place in the description here the updated image of the creature so that Esso can start working on it?

Regarding the details, I don't know what the requested polycount is, so I think that 3D artists would be more suitable for the listing of criteria. Mine would stop to "make a 3d model the closest possible to the concept" without technicalities.

**Comment by alexitsios** [comment]
Please do place what you think as acceptance criteria and the concept art that you already made.

**Comment by alexitsios** [comment]
@essothesquid if this is to be released, it'll be for episode one, so don't create this one for now.

**Comment by alexitsios** [comment]
@essothesquid I'm closing this for now since it's for another episode.

FYI @seekeroftheball
