### ISSUE TITLE
Why is ESC a standalone script?

### ISSUE THREAD

**Issue by seekeroftheball** [alexitsios/Calamity#164]
In the original controls "ESC" was handled as its own standalone script. What's the value of this? Could this be merged with our new controls and remapping system?

Check the boot loader scene for the current use of the "ESC" button script.

**Comment by josschi95** [comment]
It looks like this branch was merged, can I close this?

**Comment by alexitsios** [comment]
@seekeroftheball let us know if this should be closed.
