### ISSUE TITLE
Look up Google Sheets - GitHub API

### ISSUE THREAD

**Issue by ZidM** [alexitsios/Calamity#186]
### Description:
GitHubs interface for excel-type formatting is quite confusing and not-easy-to-use for "living documents". The asset lists are currently in Google Sheets. The intention is to convert these documents to a GitHub format when we have the final versions of the assets but it would be better if we could also put the living sheets document directly on GitHub. 

### Acceptance criteria: 
Find a way to automatically send information from Google Sheets to a GitHub sheet.

**Comment by alexitsios** [comment]
@davidebunino check out if this is needed, otherwise we can leave it as not planned.
