### ISSUE TITLE
Player Controller Assets and Audio

### ISSUE THREAD

**Issue by multihaxzors** [alexitsios/Calamity#193]
<h1>Description</h1>
Fill in the curated Player Controller Doc with all the relevant information for a player movement design document. 
<h2>Important components to add:</h2> 
<ol>
<li>How does the player turn? How fast do they turn?</li>
<li>How do they move foward/backward?</li>
<li>Are there any restrictions in how and where they can move? </li>
<li>How will the player shoot their gun?</li>
<li>How will they aim their gun? </li>
<li>How can they sprint if they can? </li>
<li>What audio is associated with movement and controls?</li>
</ol>
If you have any questions about one of the sections or what technical information is relevant please reach out to Jon.
<h1>Acceptance Criteria:</h1>
Your document is reviewed, revised and confirmed to be given out to the other departments.

<p>Edit: Work on Audio and Asset Requirements</p>

**Comment by alexitsios** [comment]
@multihaxzors @teberzin is this done?

fyi @crtherin @Unicornosplendente

**Comment by Unicornosplendente** [comment]
@alexitsios Baha confirmed is closed so I moved and closed the ticket :) fyi @crtherin
