### ISSUE TITLE
Start filling in previous discussed AI behaviours in the newly created Enemy AI doc.

### ISSUE THREAD

**Issue by multihaxzors** [alexitsios/Calamity#206]
<h1>Enemy AI Behaviour Summary</h1>
During our previous workshop, we discussed different behaviours and detection concepts for the Enemy AI. Start compiling a Design Summary for now on how the AI will behave and maybe come up with some Audio requirements and Asset Requirements.

<h2>Important Questions</h2>
<ul>
<li>What were the stages of behaviour an enemy could be in?</li>
<li>What are the different ways the enemy can detect the player?</li>
<li>How will the player lose enemy aggro?</li>
<li>How will the player know what stage of behaviour the enemy is in?</li>
<li>How does the parasite differ from the infected?</li>
<li>Will the enemy detect a player from a different room?</li>
</ul>

You may also add more questions if you can think of any other behaviour design choices. Reach out to Jonathan for any other questions.

**Comment by multihaxzors** [comment]
Feel free to look at the model I made in the previous workshop as reference.

**Comment by FreelanceSeven** [comment]
I've written out most of the Design Summary, with one or two questions still up in there air, on which we will wait for further discussion. https://docs.google.com/document/d/1V7YkwyGWI0m_Y1oxDHwvut00iNeZahSYaTigQWqmBIU/edit?usp=sharing
