### ISSUE TITLE
Copy, Paste and Translate Alex's Transition write up into the Translation Tech Doc

### ISSUE THREAD

**Issue by multihaxzors** [alexitsios/Calamity#208]
<h1>Description</h1>
Fill in the curated Transitions Doc with all the relevant information from Alex's write up on the Wiki. 
<h2>Important components to add:</h2> 
<ol>
<li>Copy over his Summary and Important Info</li>
<li>Copy and properly title his use cases?</li>
</ol>
If you have any questions about one of the sections or what technical information is relevant please reach out to Jon or Alex.
<h1>Acceptance Criteria:</h1>
Your document is reviewed by Alex and approved.

**Comment by FreelanceSeven** [comment]
I copied things over as best I can. If it need further formatting, let me know. https://docs.google.com/document/d/1Xcjq0Do6GdJH-yxLeZgQd04xr8emyStnE0CebrNRP38/edit?usp=sharing

**Comment by alexitsios** [comment]
@FreelanceSeven @multihaxzors 

I beautified the document a bit. Looks good, we just need to clarify a couple of points in a design sync before we formally close it.

**Comment by alexitsios** [comment]
Closing this since the only thing remaining is probably some formatting elements.

FYI @multihaxzors @FreelanceSeven
