### ISSUE TITLE
Define the different types of environmental hazards that will be included in the game (e.g. traps, pitfalls, toxic waste, fire, electricity)

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#26]

**Comment by alexitsios** [comment]
@teberzin do we want this? I could include it as part of the narrative, but I can exclude environmental hazards entirely.

FYI @josschi95

**Comment by teberzin** [comment]
For now, we can discard it to simplify the game. But we can still consider it for future additions if we have extra time.

**Comment by alexitsios** [comment]
@josschi95 when you have time close this issue as well.
