### ISSUE TITLE
Define the different types of health restoration items that will be available to the player (e.g. medkits, first aid sprays).

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#29]

**Comment by alexitsios** [comment]
@teberzin are we going to have only medkit or spray to simplify things?

**Comment by teberzin** [comment]
@alexitsios We can have a medkit. I will add that to the wiki.

**Comment by alexitsios** [comment]
@teberzin if this was added and its mechanic described, we should mark this as resolved.

**Comment by teberzin** [comment]
@alexitsios Yes, this is defined in the inventory items.

**Comment by alexitsios** [comment]
Closing as resolved @teberzin
