### ISSUE TITLE
Define the type of interaction (e.g. picking up items, using levers, opening doors)

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#37]

**Comment by alexitsios** [comment]
@ChristosDav @FreelanceSeven  I'm including you in this as well since the narrative beats will define the above.

**Comment by alexitsios** [comment]
@teberzin can you start working on it? For this one we'll need beats. 

also, set the acceptance criteria & a short description.

**Comment by teberzin** [comment]
I think "[Create the Player Journey regarding the acquisition of items#155](https://github.com/alexitsios/Calamity/issues/155)" contains this task now.

**Comment by alexitsios** [comment]
These are two different tasks.

**Comment by ChristosDav** [comment]
Some basic additions/modifications to Baha’s written notes in the Gameplay wiki under the “Interactions with the Items” section.
 

- The player approaches the interactable item (small glimmer effect on it) and the interaction button appears on top.

- Pressing the button will display the item’s name at the center of the screen, then be added to the inventory and removed from the game world.

- When the item is viewed in the inventory, the player has **3 options** to choose. Based on the item type, the player interacts differently.

1. The **use** option. It can be for keys, puzzle pieces and items that are used as means to progress to the next location.

2. The **equip** option. Is for weapons.

3. The **examine** option. It gives the player a detailed description of the item.

     3.1 The **closer look** option. This one can also be together with **examine**. It can be used for items hiding a message (maybe a code to unlock the cabinets) or some sort of riddle.

References taken from the following video: https://www.tiktok.com/@davidrodmad/video/7128466786122583301

What are your thoughts on these?

**Comment by Unicornosplendente** [comment]
I close this task couse according to Baha is a bit outdate

fyi @alexitsios @crtherin
