### ISSUE TITLE
Prepare Github repo for larger files (Git LFS)

### ISSUE THREAD

**Issue by DerekGooding** [alexitsios/Calamity#46]

**Comment by alexitsios** [comment]
@vitormaduro @josschi95 should we remove this?

**Comment by alexitsios** [comment]
@seekeroftheball do you think we need this? If not, can we remove it?

FYI @vitormaduro @josschi95

**Comment by seekeroftheball** [comment]
I haven't worked with it before but here's what I found. It may be necessary for our 3D artists who may have files that exceed 100mb. We should provide some documentation in the onboarding on how to setup GitHub Desktop and configure for Large Files Sizes (LFS). Save the link below for the documentation. If they have any questions they can reach out to me or the other engineers.

https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-and-customizing-github-desktop/about-git-large-file-storage-and-github-desktop

**Comment by seekeroftheball** [comment]
This is still an unknown. We haven't needed it so far but we may later. At this point it seems unlikely. Closing for now as obsolete. We can reopen later if needed.
