### ISSUE TITLE
Player States

### ISSUE THREAD

**Issue by vitormaduro** [alexitsios/Calamity#6]
### Description
Create a system to control and change the player state

### Acceptance Criteria:
The player must have a list of available states, like Walking, Shooting, Interacting, etc. Different actions will trigger different states, and these states cannot overlap (for example, no Shooting while Walking, or no Interacting while Taking Damage)

**Comment by seekeroftheball** [comment]
@vitormaduro What's the status on this?

**Comment by seekeroftheball** [comment]
Need to revisit our approach to the player controller in upcoming programming team meetup.

**Comment by seekeroftheball** [comment]
No longer relevant with ongoing design choices. Closing as obsolete.
