### ISSUE TITLE
Create an assets folder for the artists

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#60]
We'll need an assets folder so that our artists can submit their completed work there. The folder could be placed at the same level as CalamityFunigami (alongside) so there's no conflict with unity.

**Comment by alexitsios** [comment]
@DerekGooding @josschi95 fyi.

**Comment by alexitsios** [comment]
@vitormaduro can you get into it because our artists have already started working on the 3d assets?

FYI @DerekGooding @josschi95

**Comment by vitormaduro** [comment]
I created the folder inside the Assets folder, because by default Unity scopes the project to it. Creating a new folder outside the Assets folder would require navigating to that folder outside Unity to get the assets, because it would not be shown in the Editor
