### ISSUE TITLE
Create a descriptive list of all the indicative locations and items

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#61]
Acceptance criteria: 
Create a list of all the rooms the player will have to navigate in episode 1, along with a description of what each room looks like. 

A description of the rooms should include approximate size and shape, wall texture, what the purpose of the room is within the context of the story (not only what the player does in it, why does it physically exist in the world? ex. Is it an infirmary?).

**Comment by alexitsios** [comment]
@DimitrisKalyvas hey buddy, make sure you fill in the acceptance criteria so that @Pseudo-64 knows what to do when he's documenting the rooms/locations.

@FaceRadiation @josschi95 @ChristosDav  fyi.

**Comment by alexitsios** [comment]
@josschi95 mark this as resolved. 

FYI @DimitrisKalyvas @DimitrisKara7 @FaceRadiation 

I'll create a new task with the interactive / narrative elements that are required for the game.

**Comment by Pseudo-64** [comment]
Guys you might wanna remove me, becoz I am still getting emails. 🤣

**Comment by alexitsios** [comment]
I did remove you, but there are tickets that you created, so you'll receive
them till you click the unsubscribe button.
