### ISSUE TITLE
Create a list of environmental assets that will be used in the Warehouse area of Episode 1

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#71]
### Acceptance Criteria

All assets have been documented in the the https://github.com/alexitsios/Calamity/wiki/Episode-1---Level-Design-Document#warehouse-all-rooms-in-warehouses-use-the-same-wall-texture with the proper fields (Asset Name, Used In, Description, File Name)

**Comment by alexitsios** [comment]
Hey @FaceRadiation  buddy,

Can you go ahead and fill into the table all the required assets for the opening area?

FYI @DimitrisKalyvas @josschi95

**Comment by alexitsios** [comment]
@DimitrisKara7 I'm transferring this task to you as discussed in the chat.

**Comment by alexitsios** [comment]
@Pseudo-64 I transferred this task to the blocked lane. Once you have the descriptions for the warehouse, let us know here in the comments so that we transfer it back to "In Progress"

FYI @FaceRadiation @DimitrisKara7

**Comment by Pseudo-64** [comment]
Cool. Due to personal reasons it may take me until monday to finish
warehouse doc.
But I promise that by monday it will be done. I am extremely sorry for the
delay on that.
