### ISSUE TITLE
Create a concept art for magical door and magical square

### ISSUE THREAD

**Issue by Pseudo-64** [alexitsios/Calamity#74]
https://github.com/alexitsios/Calamity/wiki/Episode-1---Level-Design-Document#sub-section-magical-door---open

**Comment by alexitsios** [comment]
These are two separate tasks. @Pseudo-64

**Comment by Pseudo-64** [comment]
They fit together and complete each other. So counted them as one.

**Comment by alexitsios** [comment]
@josschi95 please resolve this one as completed.
