### ISSUE TITLE
Create character concept art for Dr. Laios (the bear)

### ISSUE THREAD

**Issue by Pseudo-64** [alexitsios/Calamity#79]
### Description 

DR. Laios is a brilliant scientist widely recognized and respected for his groundbreaking research in the field of parasitology. Driven by curiosity and a passion for discovery, he never rested on his laurels and continued to push the boundaries of what is thought possible.

Laios achieves a revolutionary breakthrough by becoming the first person to control a parasite, using his advanced knowledge to bend the tiny organism to his will, but keeping it a secret from the Organization as this is considered heresy.

During the incident, Laios is gravely wounded by the infected. Desperate to save himself, Laios uses one of the parasites he has studied and controlled to transfer his mind into it, then infests a bear from his lab for strength and resilience, hoping to escape.

He uses a shotgun and has a backpack with him.

https://github.com/alexitsios/Calamity/wiki/Story-Bible#dr-laios-the-bear

### Acceptance Criteria

The character sheet has been completed and placed into the miro board & wiki https://github.com/alexitsios/Calamity/wiki/Story-Bible#dr-laios-the-bear

**Comment by alexitsios** [comment]
@Skaers you can take over this task. Let me knew if you'd like us to establish a different kind of acceptance criteria.

**Comment by alexitsios** [comment]
@DimitrisKalyvas Will you be handling this, including rigging and animation? If that's the case, @Skaers will assign it to you once the concept is complete.

**Comment by alexitsios** [comment]
@josschi95 hey buddy if possible close this as resolved. Thank you!

FYI @Skaers
