### ISSUE TITLE
Create concept art The Parasites

### ISSUE THREAD

**Issue by Pseudo-64** [alexitsios/Calamity#80]
### Description
The parasites are highly intelligent and work together to achieve their goal of infecting and controlling a host. They are able to communicate with each other telepathically, allowing them to coordinate their attacks and take over their host as quickly and efficiently as possible. They can manipulate the host's body to suit their needs, causing them to mutate and become more monstrous in appearance.

They are also able to reproduce quickly, creating new parasites to infect new hosts. This allows them to spread rapidly and infect multiple people at once.

The parasites are not limited to infecting humans, they can also infect animals and even plants to create monstrous versions of them. The most effective way to kill the parasites is by fire.

Theoris created the parasites as a means of achieving immortality, using them to transfer their consciousness into new host bodies and evade death.

https://github.com/alexitsios/Calamity/wiki/Story-Bible#the-parasites-1

### Acceptance Criteria

The character sheet has been completed and placed into the miro board & wiki  https://github.com/alexitsios/Calamity/wiki/Story-Bible#the-parasites-1

**Comment by alexitsios** [comment]
@Skaers moving this to in progress since it's the next you'll be starting.

**Comment by alexitsios** [comment]
@Skaers closing this as completed
