### ISSUE TITLE
Create character concept art for the Acolytes

### ISSUE THREAD

**Issue by Pseudo-64** [alexitsios/Calamity#81]
### Description
Various characters who are devoted to the general cause of Theoris cause or revered mothers, often serving as scientists, helpers, or henchmen, carrying out day-to-day duties. The acolytes can be found in various areas of the game, and when the Parasites find them, they infect them.
https://github.com/alexitsios/Calamity/wiki/Story-Bible#acolytes

### Acceptance Criteria
The character sheet has been completed and placed into the miro board & wiki https://github.com/alexitsios/Calamity/wiki/Story-Bible#acolytes

**Comment by alexitsios** [comment]
@Skaers this is the last task, but it's entirely optional. Would you like us instead to start working on the landing pages (itch & steam) ?

**Comment by Skaers** [comment]
@alexitsios I can work on this, no problem!

**Comment by alexitsios** [comment]
Awesome, in the meantime I'll set up tasks for the pages (steam etc).
