### ISSUE TITLE
Create concept art for The Infected

### ISSUE THREAD

**Issue by Pseudo-64** [alexitsios/Calamity#83]
### Description

The infected, also known as the "hive-mind controlled," are individuals who have been overtaken by the parasites. They have lost control of their own minds and bodies, with the parasites controlling their actions and movements. They have become aggressive and violent, attacking any uninfected individuals they come across. Their physical appearance changes, becoming twisted and distorted as the parasites take over. They may have elongated limbs, sharp claws, and an enlarged jaw or maw for biting and attacking. They may also have additional eyes or sensory organs, as the parasites use these to better control their host. The infected are also able to move at a much faster speed and are much stronger than normal humans, making them a formidable enemy for the protagonist. They also exhibit some level of intelligence, as they can coordinate and cooperate to achieve the objectives of the hive-mind.

https://github.com/alexitsios/Calamity/wiki/Story-Bible#the-infected

### Acceptance Criteria

- The character sheet has been completed and placed into the miro board & wiki https://github.com/alexitsios/Calamity/wiki/Story-Bible#the-infected
- We should have 3-4 texture variations for them to make them distinct as their the main enemy of the game.

**Comment by alexitsios** [comment]
Closing this as completed @Skaers
