### ISSUE TITLE
Create a model for the burnt corpse from the incinerator props list

### ISSUE THREAD

**Issue by DimitrisKara7** [alexitsios/Calamity#84]
Create a rigged model for the burnt corpse prop request from the "incinerator props list" for usage. (Rigged so we can have multiple positions as a prop model)

**Comment by DimitrisKara7** [comment]
@essothesquid Hello Esso, since you're our character maker, could you take this on?

**Comment by essothesquid** [comment]
@DimitrisKara7 sure thing

**Comment by alexitsios** [comment]
@DimitrisKara7 we'll need more details regarding this task, along with the acceptance criteria.  Can you check this task for inspiration? https://github.com/users/alexitsios/projects/2/views/1?filterQuery=cassa&pane=issue&itemId=19249552 We don't need to be that descriptive for this simple task, but better give a little bit more context as to what we're asking from @essothesquid

**Comment by alexitsios** [comment]
@FaceRadiation @DimitrisKalyvas are we going to need this asset or should we remove it?

fyi @essothesquid

**Comment by alexitsios** [comment]
@josschi95 can you remove this? We won't be using it.
