### ISSUE TITLE
Create the 3D Model for Cassandra

### ISSUE THREAD

**Issue by Skaers** [alexitsios/Calamity#91]
### Description
Cassandra grew up in the Theoris Organization's monastery, raised by the organization's leaders. She was told that her parents had died, but never learned the truth about her mother Athena. The Theoris Organization considered her impure due to her skin color, and never considered that she could be the messianic figurehead or "Ultimate Being."

The Player Character appears with the Robe & tactical version. The tactical version doesn't have the mask, the pauldrons, the little vial and the ammo scattered around in her pockets, as in the concept art. 

Check the entire documentation here https://github.com/alexitsios/Calamity/wiki/Story-Bible#player-character-cassandra

![Image](https://user-images.githubusercontent.com/11029768/215743075-3de62fff-54c3-4b35-8a6a-5908421f9dcc.png)

### Acceptance Criteria: 

- Create low-poly models for Cassandra, referring to the related concept art: robed & tactical one only. The tactical 3d low poly model won't have a mask.
- The models should be textured and rigged
- The models are fully animated. Reference for the types of animation can be found at https://github.com/alexitsios/Calamity/wiki/Story-Bible#behaviors-of-player-character
- The model is uploaded into the relevant google folder.

**Comment by alexitsios** [comment]
@teberzin @Skaers @essothesquid I added additional details. Kindly check them out and verify if there are things that need to be changed.

@essothesquid kindly check the Acceptance Criteria & let us know if there's something else that needs to be included.

**Comment by alexitsios** [comment]
@teberzin check the https://github.com/alexitsios/Calamity/wiki/Story-Bible#player-character-cassandra and let me know if there's anything else you'd like me to include.

**Comment by alexitsios** [comment]
@josschi95 @vitormaduro can someone close this?
