### ISSUE TITLE
Create the Incinerator Complex

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#97]
### Description
Working on the Incinerator Complex [Incinerator Block - Morgue - Entrance to Laboratory]

Those areas are still heavily under work by me and their design is not finilized. I'm still going through layouts & designs. So the looks of the areas & their layouts are subject to change according to the level designers inputs as well.

### Acceptance Criteria
1. Textures must connect aesthetically. I source mine from Textures.com (I suggest you do the same). Search specifically for a tag called "Seamless".

2. Models must aesthetically match the texturing & detailing of each other regarding the area which they are placed in so that they don't look out of place combared to the area & to each other.

3. Try to keep a resonably low poly-count on the models & low level of detail in textures since we're going for a PS1 Aesthetic.
Keep in mind the possiblity of pixel & poly jiggle shaders that could be used to enhance the PS1 Aesthetic. **NOTE** large models of course allow for model polys & texture detail.

**Comment by DimitrisKara7** [comment]
@alexitsios @DimitrisKara7 @DimitrisKalyvas @FaceRadiation @josschi95

**Comment by alexitsios** [comment]
@josschi95 @vitormaduro please remove this!
